apiVersion: batch/v1
kind: Job
metadata:
  generateName: cpburner-noisy-
spec:
  completions: 10
  parallelism: 10
  template:
    spec:
      serviceAccountName: cpburner
      automountServiceAccountToken: true
      containers:
      - name: cpburner-noisy
        image: largeclustere2e.azurecr.io/test/cpburner:v20220630.1
        command: ["cpburner", "-resourceCount", "100000", "-resourceType", "configmap", "--concurrency", "10", "-action", "list", "-listLimit", "10000"]
      restartPolicy: Never
  backoffLimit: 4